### ISSUE TITLE
Issue installing v2.0.0

### ISSUE THREAD

**Issue by andersbogsnes** [streamsql-io/streamsql#11]
When pip installing streamsql, I get the following traceback:
```
    ERROR: Command errored out with exit status 1:
     command: /home/anders/.pyenv/versions/3.8.3/envs/streamsql/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ivw6v5du/streamsql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ivw6v5du/streamsql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sl5vwlog
         cwd: /tmp/pip-install-ivw6v5du/streamsql/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ivw6v5du/streamsql/setup.py", line 5, in <module>
        with open('requirements.txt', 'r') as req_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Looking at your tarball, you haven't included requirements.txt in your MANIFEST.in but you require it to run setup.py

**Comment by simba-git** [comment]
Thanks!
